### ISSUE TITLE
Unable to add ocm repository

### ISSUE THREAD

**Issue by xuc623671** [open-cluster-management-io/ocm#486]
helm repo add ocm https://openclustermanagement.blob.core.windows.net/releases/

![无标题_副本](https://github.com/open-cluster-management-io/ocm/assets/151613504/250e61ca-1639-4ded-a421-d89b7e4070bd)

**Comment by qiujian16** [comment]
that is a service degradation in azure we use, I am still trying to contact microsft folks.

**Comment by zhujian7** [comment]
@xuc623671 Thank you for reporting the issue, this was fixed, could you have a try with `helm repo add ocm https://open-cluster-management.io/helm-charts`?

**Comment by xuc623671** [comment]
> @xuc623671 Thank you for reporting the issue, this was fixed, could you have a try with `helm repo add ocm https://open-cluster-management.io/helm-charts`?

I have tried to use the new repo, but it still doesn't work. The error message is as follows：
Error: looks like "https://open-cluster-management.io/helm-charts" is not a valid chart repository or cannot be reached: Get "https://open-cluster-management.io/helm-charts/index.yaml": read tcp 192.168.xxx.xxxx:xxxx->185.199.110.153:443: read: connection reset by peer

**Comment by zhiweiyin318** [comment]
```
➜  ~ helm repo add ocm https://open-cluster-management.io/helm-charts
"ocm" has been added to your repositories
➜  ~
➜  ~ helm search repo ocm
NAME                             	CHART VERSION	APP VERSION	DESCRIPTION
ocm/argocd-pull-integration      	0.11.0       	1.0.0      	A Helm chart for OCM Argo CD Pull Model Integra...
ocm/cluster-gateway-addon-manager	1.4.0        	1.0.0      	A Helm chart for Cluster-Gateway Addon-Manager
ocm/cluster-proxy                	0.4.0        	1.0.0      	A Helm chart for Cluster-Proxy OCM Addon
ocm/dummy                        	1.0.2        	1.0.0      	A Helm chart for Dummy
ocm/managed-serviceaccount       	0.5.0        	1.0.0      	A Helm chart for Managed ServiceAccount Addon
ocm/multicluster-controlplane    	0.3.0        	0.3.0      	A Helm chart for multicluster-controlplane
ocm/multicluster-mesh            	0.0.1        	1.0.0      	A Helm chart for Multicluster Service Mesh OCM ...
```
@xuc623671  it looks good in my MAC and virtual machine.  could you help check your network?

**Comment by xuc623671** [comment]
I have checked the firewall and network settings, and the results of testing connectivity using telnet are:

      > [root@master local-helm-repo]# telnet  185.199.108.153 443
      > Trying 185.199.108.153...
      > Connected to 185.199.108.153.
      > Escape character is '^]'.
      > ^CConnection closed by foreign host.
      > [root@master local-helm-repo]# telnet open-cluster-management.io 443
      > Trying 185.199.108.153...
      > Connected to open-cluster-management.io.
      > Escape character is '^]'.
However, the connection result is as follows when using openssl to check the connection:
  >   [root@master ~]# openssl s_client -connect open-cluster-management.io:443
  >     CONNECTED(00000003)
  >     write:errno=104
  >     ---
  >     no peer certificate available
  >     ---
  >     No client certificate CA names sent
  >     ---
  >     SSL handshake has read 0 bytes and written 289 bytes
  >     ---
  >     New, (NONE), Cipher is (NONE)
  >     Secure Renegotiation IS NOT supported
  >     Compression: NONE
  >     Expansion: NONE
  >     No ALPN negotiated
  >     SSL-Session:
  >         Protocol  : TLSv1.2
  >         Cipher    : 0000
  >         Session-ID: 
  >         Session-ID-ctx: 
  >         Master-Key: 
  >         Key-Arg   : None
  >         Krb5 Principal: None
  >         PSK identity: None
  >         PSK identity hint: None
  >         Start Time: 1717471252
  >         Timeout   : 300 (sec)
  >         Verify return code: 0 (ok)
  >     ---


According to the output of openssl s_client, the connection is established successfully, but the peer certificate is not received. This may mean that the SSL certificate is not configured correctly on the server side, or there is a network problem that prevents the certificate from being obtained.

**Comment by xuc623671** [comment]
OK, I tested it on another machine and the result showed that the above repo is available. I need to check the network of the server.

**Comment by xuc623671** [comment]
Thanks

**Comment by xuc623671** [comment]
Thanks
